version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "ANTON"
      POSTGRES_PASSWORD: "ANTON"
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgadmin:
  postgresql:
